- src: git+https://github.com/geerlingguy/ansible-role-docker.git
  version: master
  name: docker

- src: git+https://github.com/geerlingguy/ansible-role-pip.git
  version: master
  name: pip
