- src: git+https://github.com/geerlingguy/ansible-role-docker.git
  version: master
  name: docker

- src: git+https://github.com/geerlingguy/ansible-role-pip.git
  version: master
  name: pip

- src: git+https://github.com/matthew-williams/deluge-server-webui.role.git
  version: master
  name: deluge
